data = [
    ['M E N:', 'ball', 'M E N', 'ball'],
    ["1. Saranjon behalovatman", "", "2. Dilkash va quvnoqman", ""],
    ["O‘zimni tuta olmayman tez jahlim chiqadi", "",  "Tirishqoq va ishbilarmonman ", ""],
    ["Betoqatman",  "", "Ko‘p hollarda boshlagan ishimni oxiriga yetkazmayman", ""],
    ["Odamlar bilan munosabatim keskin",  "", "O‘zimni yuqori baholayman", ""],
    ["Qat’iyatli va tashabbuskorman", "",  "Yangilikni tez o‘zlashtirib olaman", ""],
    ["O‘jar va qaysarman", "",  "Qiziqish va intilishlarim beqaror", ""],
    ["Tortishuv va bahslarda topqirman", "",  "Muvaffaqiyatsizlikni tez unutaman", ""],
    ["Bir xil tempda ishlamayman", '', "Turli sharoitga tez moslashaman", ""],
    ["Tavakkalchilikka moyilligim bor", "",  "Har qanday yangi ishga qiziqish bilan kirishaman", ""],
    ["Yomon narsalarni eslab yurmayman", "",  "Yangi ishga tez kirishaman va tez birdan ikkinchisiga o‘ta olaman", ""],
    ["Nutqim tez bo‘linuvchan ohangga ega", "",  "Agar ish qiziqtirmay qolsa tez soviyman", ""],
    ["Muvozanatsiz tez qizishib ketishga moyilman", "",  "Bir xil tempdagi ishlarda tez toliqaman", ""],
    ["Tez urishib ketadigan janjalkash", "",  "Muomalaga tez kirishaman", ""],
    ["Kamchiliklarga murosasizman", "",  "Chidamli va mehnatsevarman", ""],
    ["Ifodali mimika egasiman", "",  "Nutqim baland tez, mimika va imo-ishoralarga boy", ""],
    ["Tez  harakat qilaman va qarorga kelaman", "",  "Qiyin vaziyatda o‘zimni tuta bilaman", ""],
    ["Yangilikka muttasil intilaman", "",  "Doimo tetik kayfiyatda yuraman", ""],
    ["Harakatlarim keskin va uzilishli", "",  "Tez qarorga kelib undan voz kechaman", ""],
    ["O‘z oldimga  qo‘ygan maqsadni albatta amalga oshiraman", "",  "Tez chalg‘iyman", ""],
    ["Kayfiyatim tez o‘zgarishga moyil", "",  "Behuda shoshilaman", ""],
    ["3. Osoyishta va sovuqqonman", "",  "4. Uyatchan va tortinchoqman", ""],
    ["Ishda tartibli va izchilman", "",  "Yangi sharoitda o‘zimni yo‘qotib qo‘yaman", ""],
    ["Ehtiyotkor va aql bilan ish tutaman", "",  "Notanish kishilar bilan aloqa o‘rnatishga qiynalaman", ""],
    ["Sabr-toqat bilan kuta olaman", "",  "O‘z kuchimga ishonmayman", ""],
    ["Bo‘lar-bo‘lmas narsalar haqida gapirmay sukut saqlay olaman ", "",  "Yolg‘izlikni yoqtiraman", ""],
    ["Nutqim osoyishta bir xil tempda va hech qanday ifodali harakatlarga ega emas", "",  "Muvaffaqiyatsizlikda tez tushkunlikka berilaman", ""],
    ["Chidamli va o‘zimni tuta bilaman", "",  "Tez charchayman", ""],
    ["Boshlagan ishni oxiriga yetkaza olaman", "",  "Nutqim sekin va kuchsiz", ""],
    ["Behudaga kuch sarflamayman", "",  "Boshqalar ta’siriga tez berilaman", ""],
    ["Ish rejimi va kun tartibiga qat’iy rioya qilaman", "",  "Ta’sirlanuvchan tez yig‘layman", ""],
    ["Ehtirosni hayajonni osongina yengaman", "",  "Tanqid va maqtovni tez qabul  qilaman", ""],
    ["Tanqid va maqtovga e’tibor qilmayman", "",  "O‘zimga va boshqalarga nisbatan talabchanman", ""],
    ["Yuvosh va ko‘ngilchanman", "",  "Shubha va gumonga tez berilaman", ""],
    ["Qiziqish va munosabatlarim barqaror", "",  "Tez xafa bo‘laman va arazlayman", ""],
    ["Ishga sekin moslashib boshqa ishga o‘tishga qiynalaman", "",  "Har bir narsani o‘zimga tez qabul qilaman", ""],
    ["Munosabatlarim turli tuman", "",  "Muloqotga kirishishga qiynalaman", ""],
    ["Har bir narsada tartib va intizom bo‘lishini hohlayman", "",  "Boshqalarga fikrimni aytishni yoqtirmayman", ""],
    ["Yangi sharoitga qiyinchilik bilan moslashaman", "",  "Sust va kam faollik bilan ajralib turaman", ""],
    ["Kayfiyatim barqaror", "",  "Tez buysunaman, itoatkorman", ""],
    ["Vazmin tabiatli og‘ir-bosiqman", "",  "Boshqalarda yordam hissini uyg‘otishga harakat qilaman", ""]
]

data_2 = [
    ['Savollar', 'Javob (ha, yo‘q, ba’zida)'],
    ["Sizni oddiy yoki ish bilan bog`liq uchrashuv kutib turibdi, uchrashuv vaqtini kutish sizni asabiylashtiradimi?", ""],
    ["Sizga biror tadbir, ma`ruza o`qish, axborot yetkazish topshirilsa, bunda halovatingizni yo`qotib, hayajonlanasizmi? ", ""],
    ["Shifokor qabuliga boorishni kasal zo`rayib ketguncha cho`zib yuradigan odatingiz bormi? ", ""],
    ["Sizni boshqa shaxarga mehnat safariga jo`natishmoqda siz avvallari bu shaxarda bo`lmagansiz. Bor imkoniyatingizni ishga solib, ushbu mehnat safaridan qutilib qolishga urinasizmi? ", ""],
    ["Siz o`z kechinmalaringizni birovga u kim bo`lishidan qat`iy nazar gapirib berishni yoqtirasizmi?", ""],
    ["Ko`chada notanish insonlar sizga iltimos bilan (yo`lni ko`rsatib yuborish, vaqtni  aytib yuborish kabi iltimoslar) murojaat qilishi joningizga tegadimi?", ""],
    ["Turli yosh avlod vakillari, haqiqatdan ham bir birini tushunishlari qiyint deb o`ylaysizmi? ", ""],
    ["Tanishingiz bir necha oy oldin sizdan qarz olgan bo`lsa,unga pulni qaytarishini iltimos bilan murojaat qilishga uyalasizmi?", ""],
    ["Restoran yoki kafeda sizga sifatsiz taom keltirildi. Siz indamay likopchani jahl bilan bir chetga surib qo`yasizmi?", ""],
    ["Notanish inson bilan yolg`iz qolganda siz suhbatga kirishmaysiz, o`zingiz gap boshlamaysiz,shundaymi?", ""],
    ["Siz borgan joyda uzun navbat hosil bo`lgan bo`lsa,(do`konda, kutubxonada,kassada) niyatingizdan qaytmay qator oxiriga kelib turarmidingiz?  ", ""],
    ["Nizoli vaziyatlarni hal etish bilan shug`lanuvchi biror komissiya ishi sizni cho`chitadimi?", ""],
    ["Siz san`at asarlariga baho berishda boshqalarning fikr mulohazalarini e`tiborga olmaysiz, shundaymi?", ""],
    ["Siz yaxshi bilagan biron masala bo`yicha birov aniq xato gapirayotgan bo`lsa, bu odam bilan baxslashmasdan indamay qo`ya qolasizmi?", ""],
    ["Ish yoki o`qish yuzasidan birov muayyan muammoni hal qilishda yordam berishingizni so`rasa ensangiz qotadimi?", ""],
    ["Fikringizni og`zaki ba`yon qilgandan ko`ra yozma tarzda bildirishni ma`qul ko`rasizmi?", ""]
]
