# Generated by Django 4.2.16 on 2024-09-17 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='data_day',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
