# Generated by Django 4.2.16 on 2024-10-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_attendance_data_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honadon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='honadon/%Y/%m/%d')),
                ('student_name', models.CharField(max_length=255)),
                ('image_2', models.ImageField(upload_to='honadon/%Y/%m/%d')),
                ('dicription', models.TextField()),
            ],
            options={
                'verbose_name': 'Honadon',
                'verbose_name_plural': 'Honadons',
                'db_table': 'honadon',
            },
        ),
    ]
