# Generated by Django 4.2.16 on 2024-10-07 09:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_groupview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupview',
            unique_together={('user',)},
        ),
    ]
