# Generated by Django 5.0.3 on 2024-04-02 18:13

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_title', models.CharField(max_length=255)),
                ('journal_description', ckeditor.fields.RichTextField()),
                ('journal_image', models.ImageField(upload_to='journal/')),
                ('journal_contact', ckeditor.fields.RichTextField()),
                ('journal_pub_date', models.DateTimeField(auto_now_add=True)),
                ('journal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_journal.category')),
            ],
            options={
                'verbose_name_plural': 'Journals',
                'db_table': 'journals',
            },
        ),
    ]
